channels:
  - https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda
  - https://ftp.osuosl.org/pub/open-ce/current
  - https://ftp.osuosl.org/pub/open-ce/1.5.1
  - conda-forge
  - https://ftp.osuosl.org/pub/open-ce/current/
  - https://ftp.osuosl.org/pub/open-ce/1.8.0/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _pytorch_select=2.0
  - _tensorflow_select=2.0
  - abseil-cpp=20210324.2
  - absl-py=0.12.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - alembic=1.7.7
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow-cpp=5.0.0
  - asn1crypto=1.5.1
  - astropy=5.1
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=21.4.0
  - av=8.0.3
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=5.0.0
  - blinker=1.4
  - blosc=1.21.1
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.7.22
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=4.2.4
  - cairo=1.16.0
  - catalogue=2.0.6
  - certifi=2021.10.8
  - cffi=1.14.6
  - cfitsio=3.470
  - cftime=1.5.1.1
  - chardet=4.0.0
  - charls=2.2.0
  - charset-normalizer=2.0.12
  - clang=10.0.1
  - click=8.0.4
  - cloudpickle=1.6.0
  - colorama=0.4.4
  - conda-package-handling=1.8.1
  - configparser=5.2.0
  - cryptography=36.0.2
  - cudatoolkit=11.2.2
  - cudnn=8.1.1_11.2
  - curl=7.82.0
  - cycler=0.11.0
  - cymem=2.0.6
  - cython-blis=0.7.7
  - cytoolz=0.11.2
  - dali=1.9.0
  - dask-core=2022.4.1
  - databricks-cli=0.12.1
  - dataclasses=0.8
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dill=0.3.4
  - docker-py=5.0.3
  - docker-pycreds=0.4.0
  - entrypoints=0.4
  - expat=2.4.8
  - ffmpeg=4.2.2
  - filelock=3.6.0
  - flask=2.1.1
  - flatbuffers=1.12.1
  - flit-core=3.7.1
  - fontconfig=2.14.0
  - freeglut=3.2.2
  - freetype=2.11.0
  - frozenlist=1.3.0
  - fsspec=2022.3.0
  - future=0.18.2
  - gast=0.4.0
  - geos=3.8.0
  - gettext=0.21.0
  - gflags=2.2.2
  - giflib=5.2.1
  - git=2.35.3
  - gitdb=4.0.9
  - gitpython=3.1.27
  - glib=2.69.1
  - glob2=0.7
  - glog=0.5.0
  - gmock=1.10.0
  - gmp=6.2.1
  - gnutls=3.6.13
  - google-auth=1.23.0
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - googleapis-common-protos=1.56.0
  - gorilla=0.4.0
  - graphite2=1.3.13
  - greenlet=1.1.2
  - grpc-cpp=1.41.0
  - grpcio=1.42.0
  - gtest=1.10.0
  - gunicorn=20.1.0
  - h5py=3.2.1
  - harfbuzz=1.8.8
  - hdf4=4.2.13
  - hdf5=1.10.6
  - horovod=0.23.0
  - huggingface_hub=0.4.0
  - icu=58.2
  - idna=3.3
  - imagecodecs=2021.8.26
  - imageio=2.18.0
  - imgaug=0.4.0
  - importlib-metadata=4.11.3
  - importlib_metadata=4.11.3
  - importlib_resources=5.6.0
  - ipykernel=6.8.0
  - ipython=7.32.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - itsdangerous=2.1.2
  - jansson=2.13.1
  - jasper=2.0.14
  - jedi=0.18.1
  - jinja2=3.1.1
  - joblib=1.1.0
  - jpeg=9e
  - jpeg-turbo=2.1.0
  - jsonschema=4.4.0
  - junit-xml=1.9
  - jupyter_client=7.1.2
  - jupyter_core=4.9.1
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=1.1.0
  - jxrlib=1.1
  - keras=2.7.0
  - keras-preprocessing=1.1.2
  - keyutils=1.6.1
  - kiwisolver=1.4.2
  - krb5=1.19.3
  - lame=3.100
  - langcodes=3.3.0
  - lcms2=2.12
  - ld_impl_linux-ppc64le=2.36.1
  - lerc=3.0
  - leveldb=1.20
  - libaec=1.0.6
  - libarchive=3.5.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=10.0.1
  - libclang-cpp10=10.0.1
  - libcurl=7.82.0
  - libdeflate=1.8
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.3
  - libflac=1.3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.3.0
  - libglu=9.0.0
  - libgomp=11.2.0
  - libiconv=1.16
  - liblief=0.11.5
  - libllvm10=10.0.1
  - libllvm11=11.1.0
  - libnetcdf=4.8.1
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libogg=1.3.5
  - libopenblas=0.3.13
  - libopencv=4.5.3
  - libopus=1.3.1
  - libpng=1.6.37
  - libprotobuf=3.14.0
  - libsndfile=1.0.31
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtar=1.2.20
  - libthrift=0.15.0
  - libtiff=4.2.0
  - libutf8proc=2.7.0
  - libuuid=2.32.1
  - libvorbis=1.3.7
  - libvpx=1.7.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxgboost=1.5.1
  - libxml2=2.9.12
  - libzip=1.8.0
  - libzlib=1.2.11
  - libzopfli=1.0.3
  - llvmlite=0.38.0
  - lmdb=0.9.29
  - locket=1.0.0
  - lz4-c=1.9.3
  - lzo=2.10
  - magma=2.5.4
  - mako=1.2.0
  - markdown=3.3.3
  - markupsafe=2.1.1
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.3
  - memory_profiler=0.60.0
  - mistune=0.8.4
  - mlflow=1.2.0
  - more-itertools=8.12.0
  - mpi=1.0
  - mpi4py=3.1.3
  - multidict=5.2.0
  - murmurhash=1.0.6
  - nbclient=0.6.0
  - nbconvert=6.5.0
  - nbconvert-core=6.5.0
  - nbconvert-pandoc=6.5.0
  - nbformat=5.3.0
  - nccl=2.11.4
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - netcdf4=1.5.7
  - nettle=3.6
  - networkx=2.7.1
  - nibabel=3.2.2
  - nomkl=3.0
  - notebook=6.4.11
  - numactl=2.0.12
  - numba=0.55.1
  - numpy=1.20.3
  - numpy-base=1.20.3
  - oauthlib=3.2.0
  - olefile=0.46
  - onnx=1.10.2
  - onnxconverter-common=1.9.0
  - openblas=0.3.13
  - openblas-devel=0.3.13
  - opencv=4.5.3
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openmpi=4.1.1
  - openssl=1.1.1o
  - opt_einsum=3.3.0
  - orc=1.7.2
  - pandas=1.4.2
  - pandoc=2.11
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.2.0
  - patchelf=0.14.5
  - pathy=0.6.1
  - patsy=0.5.2
  - pcre=8.45
  - pcre2=10.37
  - perl=5.32.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=22.0.4
  - pixman=0.38.0
  - pkginfo=1.8.2
  - pluggy=0.13.1
  - portpicker=1.5.0
  - powerai-license=1.7.0
  - preshed=3.0.6
  - prometheus_client=0.14.1
  - promise=2.3
  - prompt-toolkit=3.0.29
  - protobuf=3.14.0
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - py=1.11.0
  - py-lief=0.11.5
  - py-opencv=4.5.3
  - pyarrow=5.0.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pybind11=2.9.2
  - pybind11-global=2.9.2
  - pycosat=0.6.3
  - pycparser=2.21
  - pydantic=1.8.2
  - pydicom=2.3.0
  - pyerfa=2.0.0
  - pygments=2.11.2
  - pyjwt=2.3.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.7
  - pyrsistent=0.18.1
  - pysocks=1.7.1
  - pytest=5.4.3
  - python=3.9.12
  - python-clang=10.0.1
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.3
  - python-flatbuffers=1.12
  - python-libarchive-c=3.1
  - python_abi=3.9
  - pytorch=1.10.1
  - pytorch-base=1.10.1
  - pytz=2022.1
  - pywavelets=1.3.0
  - pyyaml=5.4.1
  - pyzmq=22.3.0
  - querystring_parser=1.2.4
  - re2=2020.11.01
  - readline=8.2
  - regex=2022.3.15
  - requests=2.27.1
  - requests-oauthlib=1.3.1
  - ripgrep=13.0.0
  - rsa=4.8
  - ruamel_yaml=0.15.80
  - sacremoses=0.0.49
  - scikit-image=0.19.2
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - send2trash=1.8.0
  - sentencepiece=0.1.96
  - setuptools=60.9.3
  - shap=0.40.0
  - shapely=2.0.1
  - shellingham=1.4.0
  - simplejson=3.17.6
  - six=1.15.0
  - skl2onnx=1.10.3
  - slicer=0.0.7
  - smart_open=5.2.1
  - smmap=3.0.5
  - snappy=1.1.8
  - soupsieve=2.3.1
  - spacy=3.2.1
  - spacy-legacy=3.0.8
  - spacy-loggers=1.0.1
  - sqlalchemy=1.4.35
  - sqlite=3.38.2
  - sqlparse=0.4.2
  - srsly=2.4.2
  - statsmodels=0.13.2
  - tabulate=0.8.9
  - tenacity=8.0.1
  - tensorboard=2.7.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.6.0
  - tensorflow=2.7.0
  - tensorflow-base=2.7.0
  - tensorflow-datasets=4.3.0
  - tensorflow-estimator=2.7.0
  - tensorflow-io-gcs-filesystem=0.23.1
  - tensorflow-metadata=1.2.0
  - termcolor=1.1.0
  - terminado=0.13.3
  - thinc=8.0.12
  - threadpoolctl=3.1.0
  - tifffile=2021.7.2
  - tinycss2=1.1.1
  - tk=8.6.12
  - tokenizers=0.10.3
  - toolz=0.11.2
  - torchtext-base=0.11.1
  - torchvision=0.11.2
  - torchvision-base=0.11.2
  - tornado=6.1
  - tqdm=4.64.0
  - traitlets=5.1.1
  - transformers=4.16.2
  - typer=0.4.1
  - tzdata=2022a
  - urllib3=1.26.9
  - uwsgi=2.0.20
  - wasabi=0.9.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.3.2
  - werkzeug=2.1.1
  - wheel=0.37.1
  - widgetsnbextension=3.5.1
  - wrapt=1.12.1
  - x264=1!157.20191217
  - xgboost=1.5.1
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.7.2
  - zeromq=4.3.4
  - zfp=0.5.5
  - zipp=3.8.0
  - zlib=1.2.11
  - zstd=1.4.9

